version: '3'

services:
  database:
    image: fluiten:mysql
    build: ./assets/docker/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=verysecret
  website:
    image: fluiten:php7-apache
    build: ./
    ports:
      - 8080:8080
