-- MySQL Script generated by MySQL Workbench
-- 2019-04-29T20:35:48 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Table `reactions`.`articles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reactions`.`articles` ;

CREATE TABLE IF NOT EXISTS `reactions`.`articles` ( `arcticleID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, `title` VARCHAR(100) NOT NULL, `content` MEDIUMTEXT NOT NULL, PRIMARY KEY (`arcticleID`)) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reactions`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reactions`.`users` ;

CREATE TABLE IF NOT EXISTS `reactions`.`users` ( `userID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, `name` VARCHAR(100) NOT NULL, PRIMARY KEY (`userID`)) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reactions`.`reactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reactions`.`reactions` ;

CREATE TABLE IF NOT EXISTS `reactions`.`reactions` ( `reactionID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, `parentID` BIGINT UNSIGNED NULL DEFAULT NULL, `arcticleID` BIGINT UNSIGNED NOT NULL, `score` INT NULL DEFAULT 0, `userID` BIGINT UNSIGNED NOT NULL, `publishDate` VARCHAR(45) NOT NULL, `content` TEXT NOT NULL, PRIMARY KEY (`reactionID`), UNIQUE INDEX `reactionID_UNIQUE` (`reactionID` ASC), INDEX `fk_reactions_1_idx` (`parentID` ASC), INDEX `fk_reactions_2_idx` (`arcticleID` ASC), INDEX `fk_reactions_3_idx` (`userID` ASC), CONSTRAINT `fk_reactions_1` FOREIGN KEY (`parentID`) REFERENCES `reactions`.`reactions` (`reactionID`) ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT `fk_reactions_2` FOREIGN KEY (`arcticleID`) REFERENCES `reactions`.`articles` (`arcticleID`) ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT `fk_reactions_3` FOREIGN KEY (`userID`) REFERENCES `reactions`.`users` (`userID`) ON DELETE NO ACTION ON UPDATE NO ACTION) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reactions`.`reactionScores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reactions`.`reactionScores` ;

CREATE TABLE IF NOT EXISTS `reactions`.`reactionScores` ( `reactionID` BIGINT UNSIGNED NOT NULL, `userID` BIGINT UNSIGNED NOT NULL, `score` TINYINT NOT NULL, PRIMARY KEY (`reactionID`, `userID`), INDEX `fk_reactionScores_2_idx` (`userID` ASC), CONSTRAINT `fk_reactionScores_1` FOREIGN KEY (`reactionID`) REFERENCES `reactions`.`reactions` (`reactionID`) ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT `fk_reactionScores_2` FOREIGN KEY (`userID`) REFERENCES `reactions`.`users` (`userID`) ON DELETE NO ACTION ON UPDATE NO ACTION) ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `reactions`.`articles`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `reactions`.`articles` (`arcticleID`, `title`, `content`) VALUES (152056, 'Delfts studententeam bouwt waterstofvliegtuig', '<p>Lorem ipsum dolor sit amet</p>');

COMMIT;


-- -----------------------------------------------------
-- Data for table `reactions`.`users`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `reactions`.`users` (`userID`, `name`) VALUES (1, 'tincidunt91');
INSERT INTO `reactions`.`users` (`userID`, `name`) VALUES (2, 'TheSapienTellus');
INSERT INTO `reactions`.`users` (`userID`, `name`) VALUES (3, 'Pellentesqu3');
INSERT INTO `reactions`.`users` (`userID`, `name`) VALUES (4, '-leo-');
INSERT INTO `reactions`.`users` (`userID`, `name`) VALUES (5, 'justoNibh99');
INSERT INTO `reactions`.`users` (`userID`, `name`) VALUES (6, 'dap1bus');

COMMIT;


-- -----------------------------------------------------
-- Data for table `reactions`.`reactions`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `reactions`.`reactions` (`reactionID`, `parentID`, `arcticleID`, `score`, `userID`, `publishDate`, `content`) VALUES (1, NULL, 152056, -1, 1, '2019-04-25 16:20:00', '<p>FIPO!!</p>');
INSERT INTO `reactions`.`reactions` (`reactionID`, `parentID`, `arcticleID`, `score`, `userID`, `publishDate`, `content`) VALUES (3, 1, 152056, 0, 2, '2019-04-25 17:34:00', '<p>Lorem ipsum? Dolor fipo condimentum nibh erat, a condimentum ligula rutrum sed.</p>');
INSERT INTO `reactions`.`reactions` (`reactionID`, `parentID`, `arcticleID`, `score`, `userID`, `publishDate`, `content`) VALUES (4, 3, 152056, 1, 1, '2019-04-25 17:55:00', '<p>Suspendisse tellus sapien</p>');
INSERT INTO `reactions`.`reactions` (`reactionID`, `parentID`, `arcticleID`, `score`, `userID`, `publishDate`, `content`) VALUES (2, NULL, 152056, 3, 3, '2019-04-25 16:24:00', '<p>Lorem ipsum dolor sit amet</p>');
INSERT INTO `reactions`.`reactions` (`reactionID`, `parentID`, `arcticleID`, `score`, `userID`, `publishDate`, `content`) VALUES (5, 2, 152056, 1, 2, '2019-04-25 16:55:00', '<p>Larem ipsum dolor, dit sit dolor amet</p>');
INSERT INTO `reactions`.`reactions` (`reactionID`, `parentID`, `arcticleID`, `score`, `userID`, `publishDate`, `content`) VALUES (6, 2, 152056, 1, 4, '2019-04-25 18:12:00', '<p>Suspendisse tellus sapien</p>');

COMMIT;

